/**
 * Composite cache reader/writer + composer scaffold (plan-006 P3 stub →
 * P5 full body).
 *
 * P3 exports the schema-version constants only; the read/write/digest
 * logic is fleshed out in P5 (see this file's bottom-of-module body).
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import type { CompositeFrontmatter } from './types.js';

/** The current composite-doc schema version. */
export const COMPOSITE_CAPABILITY_SCHEMA_VERSION = 3 as const;

/**
 * Schema versions the composite reader accepts. The set is exported so
 * U-DOC and U-CMD can probe it; the reader gates entry on
 * `frontmatter.schemaVersion ∈ SUPPORTED_COMPOSITE_SCHEMA_VERSIONS`.
 */
export const SUPPORTED_COMPOSITE_SCHEMA_VERSIONS: ReadonlySet<number> = new Set<number>([
  COMPOSITE_CAPABILITY_SCHEMA_VERSION,
]);

/* ------------------------------------------------------------------ */
/* Markers (verbatim from schema-2 — composite docs reuse them so the   */
/* outer cli-agent's composeCapabilitiesSystemPrompt reader picks them */
/* up unchanged, ADR-CMP-12).                                          */
/* ------------------------------------------------------------------ */

const AUTO_GEN_START_PREFIX = '<!-- AUTO-GENERATED:START';
const AUTO_GEN_END = '<!-- AUTO-GENERATED:END -->';
const USER_NOTES_START = '<!-- USER-NOTES:START -->';
const USER_NOTES_END = '<!-- USER-NOTES:END -->';
const USER_RECIPES_START = '<!-- USER-RECIPES:START -->';
const USER_RECIPES_END = '<!-- USER-RECIPES:END -->';

/* ------------------------------------------------------------------ */
/* Read result discriminated union                                      */
/* ------------------------------------------------------------------ */

export interface CompositeDocPayload {
  readonly frontmatter: CompositeFrontmatter;
  readonly autoGeneratedBody: string;
  readonly userRecipes: string;       // body between markers (markers stripped)
  readonly userNotes: string;         // body between markers (markers stripped)
  /** Full raw document bytes as read from disk (UTF-8). */
  readonly raw: string;
}

export type ReadCompositeResult =
  | { ok: true; doc: CompositeDocPayload }
  | {
      ok: false;
      reason:
        | 'missing'
        | 'schema_version_unsupported'
        | 'integrity_failed'
        | 'cli_version_mismatch'
        | 'malformed';
      details?: string;
    };

/* ------------------------------------------------------------------ */
/* Frontmatter parser                                                   */
/* ------------------------------------------------------------------ */

/**
 * Lightweight YAML-ish parser, mirroring the existing
 * `src/agent/capabilities/cache.ts:parseFrontmatter` style. Composites'
 * frontmatter is shape-restricted (flat keys + a `members` block list +
 * a `memberDigests` block map + literal nulls) so we can hand-parse
 * without pulling in a YAML lib.
 *
 * Returns null when the document has no `---` envelope or when a
 * required field fails its type/literal contract.
 */
function parseCompositeFrontmatter(raw: string): CompositeFrontmatter | null {
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const yaml = match[1] ?? '';
  const lines = yaml.split('\n');

  let i = 0;
  // Single-line scalar fields go into `flat`. Block-list `members` and
  // block-map `memberDigests` are parsed inline because we encounter
  // them mid-stream.
  const flat: Record<string, string | null> = {};
  let members: string[] | null = null;
  let memberDigests: Record<string, string> | null = null;

  while (i < lines.length) {
    const line = lines[i] ?? '';
    if (line.length === 0 || line.startsWith('#')) {
      i++;
      continue;
    }
    const colon = line.indexOf(':');
    if (colon <= 0) {
      i++;
      continue;
    }
    const key = line.slice(0, colon).trim();
    let value = line.slice(colon + 1).trim();

    // Block-list shape: `members:` followed by `  - name` lines.
    if (key === 'members' && value === '') {
      const arr: string[] = [];
      i++;
      while (i < lines.length) {
        const lookahead = lines[i] ?? '';
        const m = lookahead.match(/^\s+-\s+(.+)$/);
        if (!m) break;
        let item = m[1]!.trim();
        if (item.startsWith('"') && item.endsWith('"')) item = item.slice(1, -1);
        arr.push(item);
        i++;
      }
      members = arr;
      continue;
    }

    // Block-map shape: `memberDigests:` followed by `  <name>: <hex>` lines.
    if (key === 'memberDigests' && value === '') {
      const obj: Record<string, string> = {};
      i++;
      while (i < lines.length) {
        const lookahead = lines[i] ?? '';
        const m = lookahead.match(/^\s+([A-Za-z][A-Za-z0-9_-]*):\s+(.+)$/);
        if (!m) break;
        const k = m[1]!;
        let v = m[2]!.trim();
        if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
        obj[k] = v;
        i++;
      }
      memberDigests = obj;
      continue;
    }

    // Strip surrounding quotes from scalar values.
    if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
      value = value.slice(1, -1);
    }
    flat[key] = value;
    i++;
  }

  // Validate required scalars + literal-typed fields.
  const sv = Number(flat['schemaVersion'] ?? '');
  if (sv !== 3) return null;
  const composite = String(flat['composite'] ?? '');
  if (composite !== 'true') return null;
  const compositeName = String(flat['compositeName'] ?? '');
  if (compositeName.length === 0) return null;
  if (members === null) return null;
  if (memberDigests === null) return null;
  const synthesizedAt = String(flat['synthesizedAt'] ?? '');
  if (synthesizedAt.length === 0) return null;
  const syntheticDigest = String(flat['syntheticDigest'] ?? '');
  if (syntheticDigest.length === 0) return null;
  const cliAgentVersion = String(flat['cliAgentVersion'] ?? '');
  if (cliAgentVersion.length === 0) return null;
  const synthesisModel = String(flat['synthesisModel'] ?? '');
  if (synthesisModel.length === 0) return null;
  const activeProfileRaw = flat['activeProfile'];
  const activeProfile: string | null =
    activeProfileRaw === undefined || activeProfileRaw === 'null'
      ? null
      : String(activeProfileRaw);
  // manRef / manPagePath MUST be the literal `null` for composites.
  if (flat['manRef'] !== 'null') return null;
  if (flat['manPagePath'] !== 'null') return null;

  return {
    schemaVersion: 3,
    composite: true,
    compositeName,
    members: Object.freeze([...members]),
    memberDigests: Object.freeze({ ...memberDigests }),
    synthesizedAt,
    syntheticDigest,
    cliAgentVersion,
    synthesisModel,
    activeProfile,
    manRef: null,
    manPagePath: null,
  };
}

/* ------------------------------------------------------------------ */
/* Section extractors                                                   */
/* ------------------------------------------------------------------ */

function extractAutoGenBody(raw: string): string {
  const start = raw.indexOf(AUTO_GEN_START_PREFIX);
  const end = raw.indexOf(AUTO_GEN_END);
  if (start === -1 || end === -1) return '';
  // Skip past the start marker line (find the next \n).
  const bodyStart = raw.indexOf('\n', start) + 1;
  return raw.slice(bodyStart, end).trim();
}

function extractTaggedBody(raw: string, startTag: string, endTag: string): string {
  const s = raw.indexOf(startTag);
  const e = raw.indexOf(endTag);
  if (s === -1 || e === -1 || e < s) return '';
  return raw.slice(s + startTag.length, e).trim();
}

/**
 * Extract the USER-NOTES block (markers included) from an arbitrary
 * composite doc text. Mirrors `composeMarkdown.ts:extractUserNotes`
 * but lives here so the composite reader/writer don't depend on the
 * schema-2 helper module.
 */
export function extractCompositeUserNotes(doc: string): string {
  const start = doc.indexOf(USER_NOTES_START);
  const end = doc.indexOf(USER_NOTES_END);
  if (start === -1 || end === -1) return '';
  return doc.slice(start, end + USER_NOTES_END.length);
}

/**
 * Extract the USER-RECIPES block (markers included) from an arbitrary
 * composite doc text.
 */
export function extractCompositeUserRecipes(doc: string): string {
  const start = doc.indexOf(USER_RECIPES_START);
  const end = doc.indexOf(USER_RECIPES_END);
  if (start === -1 || end === -1) return '';
  return doc.slice(start, end + USER_RECIPES_END.length);
}

/* ------------------------------------------------------------------ */
/* Canonicalisation + digests                                           */
/* ------------------------------------------------------------------ */

/**
 * Canonicalise a member capability doc for digest computation /
 * Stage-1 prompt input. The single source of truth: both writer (when
 * populating `memberDigests`) and reader (when comparing for cache
 * invalidation) call this helper so the same inputs always hash to
 * the same bytes.
 *
 * Steps (per project-design.md §14.C):
 *   1. Strip everything between USER-RECIPES markers (markers included).
 *   2. Strip everything between USER-NOTES markers (markers included).
 *   3. Strip trailing whitespace from each remaining line; normalise
 *      line endings to `\n`.
 */
export function canonicaliseMemberDoc(memberDocText: string): string {
  let out = memberDocText.replace(/\r\n/g, '\n');

  // Strip USER-RECIPES section (markers included).
  const recipesStart = out.indexOf(USER_RECIPES_START);
  const recipesEnd = out.indexOf(USER_RECIPES_END);
  if (recipesStart !== -1 && recipesEnd !== -1 && recipesEnd > recipesStart) {
    const after = out.indexOf('\n', recipesEnd + USER_RECIPES_END.length);
    const cutEnd = after === -1 ? recipesEnd + USER_RECIPES_END.length : after + 1;
    out = out.slice(0, recipesStart) + out.slice(cutEnd);
  }
  // Strip USER-NOTES section (markers included).
  const notesStart = out.indexOf(USER_NOTES_START);
  const notesEnd = out.indexOf(USER_NOTES_END);
  if (notesStart !== -1 && notesEnd !== -1 && notesEnd > notesStart) {
    const after = out.indexOf('\n', notesEnd + USER_NOTES_END.length);
    const cutEnd = after === -1 ? notesEnd + USER_NOTES_END.length : after + 1;
    out = out.slice(0, notesStart) + out.slice(cutEnd);
  }

  // Strip trailing whitespace per line; collapse trailing blank
  // tail to a single trailing `\n` for digest stability.
  const lines = out.split('\n').map((l) => l.replace(/[ \t]+$/u, ''));
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  return lines.join('\n') + '\n';
}

/**
 * sha256 first 16 hex of the canonicalised member-doc bytes. Used for
 * `memberDigests` and as one input to the composite cache key.
 */
export function computeMemberDocDigest(memberDocText: string): string {
  const canonical = canonicaliseMemberDoc(memberDocText);
  return crypto.createHash('sha256').update(canonical).digest('hex').slice(0, 16);
}

/**
 * Compute the syntheticDigest for a composite doc. The digest is keyed
 * to the canonicalised body (frontmatter + AUTO-GENERATED + USER-*
 * sections excluded — i.e., the bytes that live OUTSIDE the syntheticDigest
 * field itself, with USER-* stripped).
 *
 * Plan-006 §14.C definition: `sha256(JSON.stringify(canonicalInputs))`
 * where `canonicalInputs = { schemaVersion, compositeName, members,
 * memberDigests, cliAgentVersion, synthesisModel }`. This helper is
 * exposed for U-DOC + U-SYNTH so both compute the same value the same
 * way.
 *
 * Two callers:
 *   - U-DOC's `composeCompositeDoc` + writer use it to populate the
 *     frontmatter field.
 *   - The reader uses it to verify integrity on read.
 */
export function computeSyntheticDigest(canonicalisedBody: string): string {
  return crypto.createHash('sha256').update(canonicalisedBody).digest('hex').slice(0, 16);
}

/**
 * Build the canonical input string the syntheticDigest hashes over.
 * Inputs-only — Stage-2 LLM response content does NOT enter the
 * digest, per §14.C.
 */
export function canonicaliseSyntheticInputs(input: {
  readonly schemaVersion: number;
  readonly compositeName: string;
  readonly members: readonly string[];
  readonly memberDigests: Readonly<Record<string, string>>;
  readonly cliAgentVersion: string;
  readonly synthesisModel: string;
}): string {
  // JSON.stringify with explicit sort to make the byte stream
  // deterministic across V8 versions / object-key insertion orders.
  const sortedDigests: Record<string, string> = {};
  for (const k of Object.keys(input.memberDigests).sort()) {
    sortedDigests[k] = input.memberDigests[k]!;
  }
  return JSON.stringify({
    schemaVersion: input.schemaVersion,
    compositeName: input.compositeName,
    members: [...input.members].sort(),
    memberDigests: sortedDigests,
    cliAgentVersion: input.cliAgentVersion,
    synthesisModel: input.synthesisModel,
  });
}

/* ------------------------------------------------------------------ */
/* Reader                                                               */
/* ------------------------------------------------------------------ */

/**
 * Read a composite doc from disk and parse + validate it. Returns a
 * tagged result so callers can branch on the failure reason without
 * pattern-matching strings.
 *
 * `expectedCliAgentVersion` (optional, ADR-CMP-8 / OQ-4): when
 * supplied, a recorded `cliAgentVersion` that does NOT match the
 * expected version returns `cli_version_mismatch` so the caller can
 * trigger re-synthesis on the next pipeline run.
 *
 * Integrity check: the recorded `syntheticDigest` is recomputed from
 * the parsed frontmatter inputs; mismatch → `integrity_failed`.
 */
export async function readCompositeDoc(
  filePath: string,
  opts: { expectedCliAgentVersion?: string } = {},
): Promise<ReadCompositeResult> {
  let raw: string;
  try {
    raw = await fsp.readFile(filePath, 'utf8');
  } catch (e) {
    if ((e as { code?: string }).code === 'ENOENT') return { ok: false, reason: 'missing' };
    throw e;
  }

  const fm = parseCompositeFrontmatter(raw);
  if (fm === null) {
    return { ok: false, reason: 'malformed', details: 'frontmatter parse failed or required field missing' };
  }
  if (!SUPPORTED_COMPOSITE_SCHEMA_VERSIONS.has(fm.schemaVersion)) {
    return {
      ok: false,
      reason: 'schema_version_unsupported',
      details: `schemaVersion=${String(fm.schemaVersion)} not in supported set`,
    };
  }

  // Integrity check: recompute syntheticDigest from canonical inputs.
  const recomputed = computeSyntheticDigest(
    canonicaliseSyntheticInputs({
      schemaVersion: fm.schemaVersion,
      compositeName: fm.compositeName,
      members: fm.members,
      memberDigests: fm.memberDigests,
      cliAgentVersion: fm.cliAgentVersion,
      synthesisModel: fm.synthesisModel,
    }),
  );
  if (recomputed !== fm.syntheticDigest) {
    return {
      ok: false,
      reason: 'integrity_failed',
      details: `syntheticDigest mismatch: recorded=${fm.syntheticDigest} recomputed=${recomputed}`,
    };
  }

  // CLI-version policy (ADR-CMP-8): a recorded version older than the
  // running version → strict cache miss. Caller decides whether to
  // re-synthesise; we just signal the mismatch.
  if (
    opts.expectedCliAgentVersion !== undefined &&
    opts.expectedCliAgentVersion !== fm.cliAgentVersion
  ) {
    return {
      ok: false,
      reason: 'cli_version_mismatch',
      details: `recorded=${fm.cliAgentVersion} running=${opts.expectedCliAgentVersion}`,
    };
  }

  return {
    ok: true,
    doc: {
      frontmatter: fm,
      autoGeneratedBody: extractAutoGenBody(raw),
      userRecipes: extractTaggedBody(raw, USER_RECIPES_START, USER_RECIPES_END),
      userNotes: extractTaggedBody(raw, USER_NOTES_START, USER_NOTES_END),
      raw,
    },
  };
}

/* ------------------------------------------------------------------ */
/* Writer (atomic temp+rename, mode 0600)                               */
/* ------------------------------------------------------------------ */

/**
 * Atomically write a composite doc to disk at mode 0o600. Uses the
 * same temp-then-rename pattern as `posix-wrapper-shim-design.md` §10
 * so a crash mid-write never leaves a half-written file.
 *
 * The caller is expected to pass a fully-formed doc string (from
 * `composeCompositeDoc`). This writer does NOT recompute or inject
 * the syntheticDigest — that is the composer's job (so the digest
 * matches the body bytes exactly).
 */
export async function writeCompositeDoc(filePath: string, doc: string): Promise<void> {
  const dir = path.dirname(filePath);
  await fsp.mkdir(dir, { recursive: true, mode: 0o700 });
  // Use a per-process tmp suffix so concurrent writers in the same
  // dir don't collide. `process.pid` + monotonic counter is overkill
  // for v1 (we don't expect concurrent composite synthesis); pid +
  // hrtime is enough.
  const tmpPath = `${filePath}.tmp.${String(process.pid)}.${process.hrtime.bigint().toString(36)}`;
  await fsp.writeFile(tmpPath, doc, { encoding: 'utf8', mode: 0o600 });
  try {
    await fsp.rename(tmpPath, filePath);
  } catch (e) {
    // Best-effort cleanup; tolerate if the tmp was already gone.
    try { await fsp.unlink(tmpPath); } catch { /* ignored */ }
    throw e;
  }
  try { await fsp.chmod(filePath, 0o600); } catch { /* tolerated on Windows */ }
}

/* ------------------------------------------------------------------ */
/* Mirror copy → <capabilitiesDir>/<id>.md                              */
/* ------------------------------------------------------------------ */

/**
 * Copy the canonical composite doc into `<capabilitiesDir>/<id>.md`
 * so the existing `composeCapabilitiesSystemPrompt` reader picks it
 * up transparently (ADR-CMP-12). We use **copy** rather than symlink
 * for two reasons documented in the investigation §"Pitfalls watched
 * for":
 *
 *   1. Some filesystems (Windows, certain CI containers) restrict
 *      symlink creation; copy is universally portable.
 *   2. A symlink would couple the consumer's read-time view to writer
 *      lock state — a partial write of the canonical doc would be
 *      visible immediately. The copy is performed AFTER the canonical
 *      atomic write succeeds, so the mirror is always a complete
 *      snapshot.
 *
 * Returns the absolute path of the mirror file.
 */
export async function mirrorCompositeDocToCapabilities(
  compositeDocPath: string,
  capabilitiesDir: string,
  compositeName: string,
): Promise<string> {
  const dest = path.join(capabilitiesDir, `${compositeName}.md`);
  // `fs.copyFile` is atomic for the whole-file replace on POSIX (single
  // syscall under the hood when src/dst are on the same fs); fall back
  // to read+write for the cross-device case.
  await fsp.mkdir(path.dirname(dest), { recursive: true, mode: 0o700 });
  try {
    await fsp.copyFile(compositeDocPath, dest);
  } catch (e) {
    if ((e as { code?: string }).code === 'EXDEV') {
      const buf = await fsp.readFile(compositeDocPath);
      const tmp = `${dest}.tmp.${String(process.pid)}.${process.hrtime.bigint().toString(36)}`;
      await fsp.writeFile(tmp, buf, { mode: 0o600 });
      await fsp.rename(tmp, dest);
    } else {
      throw e;
    }
  }
  try { await fsp.chmod(dest, 0o600); } catch { /* tolerated */ }
  return dest;
}

// Sync-import marker so `import 'node:fs'` is not stripped by tree-shaking.
// (`fs` is used implicitly by Node's promise APIs we depend on for
// constants, but we don't need the namespace at runtime.) Keeping the
// reference visible for future fs.constants needs.
void fs.constants;
