/**
 * Co-located unit tests for `shim-writer.ts` (plan-006 P6 / U-WRAPPER).
 *
 * Coverage:
 *   - shim text correctness (snapshot with the timestamp masked)
 *   - atomic-write semantics (tmp cleaned up on writeFile failure;
 *     final file untouched)
 *   - mode 0o755 verified via fsp.stat
 *   - idempotent regeneration (re-run produces same content modulo the
 *     timestamp comment)
 *   - nvm/volta/asdf detection emits warnings (non-fatal)
 *   - member-name escaping for awkward characters (space, single quote,
 *     backslash)
 *   - generatePathSymlink: happy path, collision-without-force,
 *     collision-with-force, on-PATH advisory.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fsp from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

import {
  generateCompositeWrapperShim,
  generatePathSymlink,
} from './shim-writer.js';
import type { CompositeWrapperShimSpec } from './types.js';

/* ------------------------------------------------------------------ */
/* Fixture helpers                                                     */
/* ------------------------------------------------------------------ */

async function makeTmpDir(prefix: string): Promise<string> {
  return fsp.mkdtemp(path.join(os.tmpdir(), `${prefix}-`));
}

function makeSpec(overrides: Partial<CompositeWrapperShimSpec> = {}): CompositeWrapperShimSpec {
  return {
    compositeName: 'foo-plus-bar',
    members: ['foo-cli', 'bar-cli'],
    cliAgentBinPath: '/usr/local/bin/cli-agent',
    capabilityDocPath: '/home/u/.tool-agents/cli-agent/capabilities/foo-plus-bar.md',
    shimDir: '/tmp/never-used-default',
    synthesizedAt: '2026-05-02T12:00:00.000Z',
    ...overrides,
  };
}

/** Mask the timestamp comment so snapshot comparisons are stable. */
function maskTimestamp(text: string): string {
  return text.replace(
    /^# Generated by cli-agent composite-synthesize @ [^;]+; composite=/m,
    '# Generated by cli-agent composite-synthesize @ <ISO>; composite=',
  );
}

/* ------------------------------------------------------------------ */
/* generateCompositeWrapperShim                                        */
/* ------------------------------------------------------------------ */

describe('generateCompositeWrapperShim — shim text', () => {
  let outDir: string;

  beforeEach(async () => {
    outDir = await makeTmpDir('shim-writer-text');
  });

  afterEach(async () => {
    await fsp.rm(outDir, { recursive: true, force: true });
  });

  it('matches the recommended POSIX template (snapshot with masked timestamp)', async () => {
    const result = await generateCompositeWrapperShim(makeSpec({ shimDir: outDir }));
    const body = await fsp.readFile(result.path, 'utf8');
    const masked = maskTimestamp(body);

    expect(masked).toMatchInlineSnapshot(`
      "#!/bin/sh
      # Generated by cli-agent composite-synthesize @ <ISO>; composite=foo-plus-bar
      # cli-agent composite wrapper — foo-plus-bar
      # DO NOT HAND-EDIT — regenerate with:
      #   cli-agent --treat-as-tool --regenerate-capabilities --composite-name foo-plus-bar
      basedir=$(dirname "$(echo "$0" | sed -e 's,\\\\,/,g')")
      DOC='/home/u/.tool-agents/cli-agent/capabilities/foo-plus-bar.md'
      case "\${1:-}" in
        --help|-h)
          if [ ! -r "$DOC" ]; then
            echo "composite cache stale; re-run: cli-agent --treat-as-tool --regenerate-capabilities --composite-name foo-plus-bar" >&2
            exit 6
          fi
          exec cat "$DOC"
          ;;
      esac
      exec '/usr/local/bin/cli-agent' --tool 'foo-cli' --tool 'bar-cli' "$@"
      "
    `);
  });

  it('uses #!/bin/sh (no bash) and exec for the cli-agent invocation', async () => {
    const result = await generateCompositeWrapperShim(makeSpec({ shimDir: outDir }));
    const body = await fsp.readFile(result.path, 'utf8');
    expect(body.startsWith('#!/bin/sh\n')).toBe(true);
    // Must NOT include set -euo pipefail (research §3).
    expect(body).not.toMatch(/set\s+-e/);
    expect(body).not.toMatch(/pipefail/);
    // The terminal exec line uses absolute cli-agent path.
    expect(body).toMatch(/^exec '\/usr\/local\/bin\/cli-agent' /m);
  });

  it('bakes additionalArgs (e.g. --no-agent-tools) before "$@"', async () => {
    const result = await generateCompositeWrapperShim(
      makeSpec({ shimDir: outDir }),
      { additionalArgs: ['--no-agent-tools', '--allow-mutations', '--per-tool-budget', '65536'] },
    );
    const body = await fsp.readFile(result.path, 'utf8');
    // Each baked-in arg is single-quoted; "$@" remains the trailing token.
    expect(body).toContain(
      "exec '/usr/local/bin/cli-agent' --tool 'foo-cli' --tool 'bar-cli' " +
        "'--no-agent-tools' '--allow-mutations' '--per-tool-budget' '65536' \"$@\"",
    );
  });

  it('escapes member names with awkward characters safely', async () => {
    const result = await generateCompositeWrapperShim(
      makeSpec({
        shimDir: outDir,
        // Names a future relaxation might allow. Today's regex disallows
        // these but the generator must not regress if it ever changes.
        members: ["weird name", "it's", 'with\\backslash'],
      }),
    );
    const body = await fsp.readFile(result.path, 'utf8');
    expect(body).toContain("--tool 'weird name'");
    // Single-quote in member name → close, escaped quote, reopen.
    expect(body).toContain("--tool 'it'\\''s'");
    // Backslash is literal inside single quotes — no escaping needed.
    expect(body).toContain("--tool 'with\\backslash'");
  });

  it('escapes a doc path containing spaces and a single quote', async () => {
    const result = await generateCompositeWrapperShim(
      makeSpec({
        shimDir: outDir,
        capabilityDocPath: "/home/user's dir/doc.md",
      }),
    );
    const body = await fsp.readFile(result.path, 'utf8');
    expect(body).toContain("DOC='/home/user'\\''s dir/doc.md'");
  });
});

/* ------------------------------------------------------------------ */
/* mode + atomicity                                                    */
/* ------------------------------------------------------------------ */

describe('generateCompositeWrapperShim — atomic write & mode', () => {
  let outDir: string;
  beforeEach(async () => {
    outDir = await makeTmpDir('shim-writer-atomic');
  });
  afterEach(async () => {
    await fsp.rm(outDir, { recursive: true, force: true });
  });

  it('writes the shim with mode 0o755', async () => {
    const result = await generateCompositeWrapperShim(makeSpec({ shimDir: outDir }));
    expect(result.mode).toBe(0o755);
    const stat = await fsp.stat(result.path);
    // Mask off the file-type bits; only the permission bits matter.
    expect(stat.mode & 0o777).toBe(0o755);
  });

  it('cleans up the .tmp file when the rename fails (atomic-write semantics)', async () => {
    // Strategy: pre-create a directory at the FINAL path; rename(file → dir)
    // with a non-empty dir fails on POSIX (EISDIR / ENOTEMPTY / EEXIST,
    // depending on the platform). The writeFile of the .tmp succeeds, so
    // the cleanup path of the generator is exercised.
    const spec = makeSpec({ shimDir: outDir });
    const finalPath = path.join(outDir, spec.compositeName);
    await fsp.mkdir(finalPath);
    // Make the dir non-empty so rename can't atomically replace it on Linux.
    await fsp.writeFile(path.join(finalPath, 'sentinel'), 'x', 'utf8');

    await expect(generateCompositeWrapperShim(spec)).rejects.toThrow(/failed to write shim/);

    // Tmp file must NOT exist (cleaned up).
    const tmpPath = `${finalPath}.tmp`;
    await expect(fsp.stat(tmpPath)).rejects.toMatchObject({ code: 'ENOENT' });

    // Final path is unchanged (still our pre-existing directory).
    const stat = await fsp.lstat(finalPath);
    expect(stat.isDirectory()).toBe(true);
  });

  it('cleans up the .tmp file when writeFile itself fails (forced via read-only dir)', async () => {
    // Sub-strategy: chmod the parent dir to read-only (0o555) AFTER the
    // generator ensures it exists — but the generator does an mkdir first
    // with mode 0o700. We sidestep this by giving the generator a path
    // that already exists as a read-only directory.
    const lockedDir = path.join(outDir, 'locked');
    await fsp.mkdir(lockedDir, { mode: 0o500 });
    try {
      const spec = makeSpec({ shimDir: lockedDir });
      await expect(generateCompositeWrapperShim(spec)).rejects.toThrow(/failed to write shim/);
      // Tmp file should not exist (either never created, or cleaned up).
      const tmpPath = path.join(lockedDir, `${spec.compositeName}.tmp`);
      await expect(fsp.stat(tmpPath)).rejects.toMatchObject({ code: 'ENOENT' });
    } finally {
      // Restore writability so afterEach's rm() can succeed.
      await fsp.chmod(lockedDir, 0o700);
    }
  });

  it('idempotent: re-running with the same spec produces byte-identical content (modulo timestamp)', async () => {
    const spec1 = makeSpec({ shimDir: outDir, synthesizedAt: '2026-05-02T00:00:00.000Z' });
    const spec2 = makeSpec({ shimDir: outDir, synthesizedAt: '2026-05-03T00:00:00.000Z' });

    const r1 = await generateCompositeWrapperShim(spec1);
    const body1 = await fsp.readFile(r1.path, 'utf8');

    const r2 = await generateCompositeWrapperShim(spec2);
    const body2 = await fsp.readFile(r2.path, 'utf8');

    expect(r1.path).toBe(r2.path);
    expect(maskTimestamp(body1)).toBe(maskTimestamp(body2));
    // The bodies differ only in the timestamp comment.
    expect(body1).not.toBe(body2);
  });

  it('atomic rename: the final file at <outputDir>/<name> exists with full content (no half-written window)', async () => {
    const result = await generateCompositeWrapperShim(makeSpec({ shimDir: outDir }));
    const body = await fsp.readFile(result.path, 'utf8');
    expect(body.startsWith('#!/bin/sh\n')).toBe(true);
    expect(body.endsWith('\n')).toBe(true);
    // No leftover .tmp.
    await expect(fsp.stat(`${result.path}.tmp`)).rejects.toMatchObject({ code: 'ENOENT' });
  });
});

/* ------------------------------------------------------------------ */
/* version-manager warning                                             */
/* ------------------------------------------------------------------ */

describe('generateCompositeWrapperShim — nvm/volta/asdf detection', () => {
  let outDir: string;
  beforeEach(async () => {
    outDir = await makeTmpDir('shim-writer-vm');
  });
  afterEach(async () => {
    await fsp.rm(outDir, { recursive: true, force: true });
  });

  it.each([
    ['nvm', '/Users/x/.nvm/versions/node/v22.0.0/bin/cli-agent'],
    ['volta', '/Users/x/.volta/bin/cli-agent'],
    ['asdf', '/Users/x/.asdf/installs/nodejs/22.0.0/bin/cli-agent'],
  ])('warns when cliAgentBinPath is under %s', async (manager, binPath) => {
    const result = await generateCompositeWrapperShim(
      makeSpec({ shimDir: outDir, cliAgentBinPath: binPath }),
    );
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings.join(' ')).toContain(manager);
    // Shim still emitted (non-fatal warning per OQ-6).
    const body = await fsp.readFile(result.path, 'utf8');
    expect(body).toContain(`exec '${binPath}'`);
  });

  it('does NOT warn for a stable global install path', async () => {
    const result = await generateCompositeWrapperShim(
      makeSpec({ shimDir: outDir, cliAgentBinPath: '/usr/local/bin/cli-agent' }),
    );
    expect(result.warnings).toEqual([]);
  });
});

/* ------------------------------------------------------------------ */
/* generatePathSymlink                                                 */
/* ------------------------------------------------------------------ */

describe('generatePathSymlink', () => {
  let workDir: string;
  let shimDir: string;
  let linkDir: string;
  let shimPath: string;

  beforeEach(async () => {
    workDir = await makeTmpDir('shim-writer-symlink');
    shimDir = path.join(workDir, 'shims');
    linkDir = path.join(workDir, 'bin');
    await fsp.mkdir(shimDir, { recursive: true });
    // Synthesise an actual shim file the symlink will point at.
    const result = await generateCompositeWrapperShim(makeSpec({ shimDir }));
    shimPath = result.path;
  });

  afterEach(async () => {
    await fsp.rm(workDir, { recursive: true, force: true });
  });

  it('happy path: creates a symlink in the requested directory', async () => {
    const r = await generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir });
    expect(r.symlinkPath).toBe(path.join(linkDir, 'foo-plus-bar'));
    const lstat = await fsp.lstat(r.symlinkPath);
    expect(lstat.isSymbolicLink()).toBe(true);
    const target = await fsp.readlink(r.symlinkPath);
    expect(target).toBe(shimPath);
  });

  it('idempotent: re-running with an already-correct symlink is a no-op', async () => {
    await generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir });
    const r = await generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir });
    expect(r.symlinkPath).toBe(path.join(linkDir, 'foo-plus-bar'));
    const target = await fsp.readlink(r.symlinkPath);
    expect(target).toBe(shimPath);
  });

  it('refuses to clobber an existing regular file when force is false', async () => {
    await fsp.mkdir(linkDir, { recursive: true });
    const collidePath = path.join(linkDir, 'foo-plus-bar');
    await fsp.writeFile(collidePath, 'pre-existing real binary', 'utf8');
    await expect(
      generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir }),
    ).rejects.toThrow(/already exists/);
    // Original file untouched.
    expect(await fsp.readFile(collidePath, 'utf8')).toBe('pre-existing real binary');
  });

  it('replaces an existing regular file when force=true and warns about it', async () => {
    await fsp.mkdir(linkDir, { recursive: true });
    const collidePath = path.join(linkDir, 'foo-plus-bar');
    await fsp.writeFile(collidePath, 'pre-existing real binary', 'utf8');

    const r = await generatePathSymlink(shimPath, 'foo-plus-bar', {
      dir: linkDir,
      force: true,
    });
    expect(r.symlinkPath).toBe(collidePath);
    const lstat = await fsp.lstat(collidePath);
    expect(lstat.isSymbolicLink()).toBe(true);
    expect(r.warnings.some((w) => /Replaced a non-symlink file/.test(w))).toBe(true);
  });

  it('replaces a stale symlink (pointing elsewhere) when force=true', async () => {
    await fsp.mkdir(linkDir, { recursive: true });
    const otherTarget = path.join(workDir, 'other-bin');
    await fsp.writeFile(otherTarget, '#!/bin/sh\necho other\n', { mode: 0o755 });
    const collidePath = path.join(linkDir, 'foo-plus-bar');
    await fsp.symlink(otherTarget, collidePath);

    const r = await generatePathSymlink(shimPath, 'foo-plus-bar', {
      dir: linkDir,
      force: true,
    });
    expect(await fsp.readlink(r.symlinkPath)).toBe(shimPath);
  });

  it('warns when the symlink directory is not on $PATH', async () => {
    const original = process.env['PATH'];
    process.env['PATH'] = '/usr/bin:/bin'; // does not contain linkDir
    try {
      const r = await generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir });
      expect(r.warnings.some((w) => /not on \$PATH/.test(w))).toBe(true);
    } finally {
      if (original === undefined) delete process.env['PATH'];
      else process.env['PATH'] = original;
    }
  });

  it('does NOT warn about $PATH when the symlink directory is on $PATH', async () => {
    const original = process.env['PATH'];
    process.env['PATH'] = `${linkDir}:/usr/bin:/bin`;
    try {
      const r = await generatePathSymlink(shimPath, 'foo-plus-bar', { dir: linkDir });
      expect(r.warnings.some((w) => /not on \$PATH/.test(w))).toBe(false);
    } finally {
      if (original === undefined) delete process.env['PATH'];
      else process.env['PATH'] = original;
    }
  });

  it('rejects a name containing a path separator', async () => {
    await expect(
      generatePathSymlink(shimPath, 'evil/name', { dir: linkDir }),
    ).rejects.toThrow(/invalid name/);
  });
});
