/**
 * Composite intelligent tools — type contracts (plan-006 §14.D).
 *
 * LEAF MODULE: only stdlib types + base AgentConfig / Logger / langchain
 * message types may be imported. No imports of other composite modules
 * — this is the foundation every other unit depends on, so it MUST not
 * cycle.
 *
 * The interfaces below are the load-bearing contract between the seven
 * Phase-6 parallel implementation units (§14.P). No unit may broaden a
 * return shape, narrow an input, or add required parameters without
 * explicit cross-unit coordination.
 */

import type { BaseMessage } from '@langchain/core/messages';
import type { BaseChatModel } from '@langchain/core/language_models/chat_models';
import type { AgentConfig } from '../../config/agent-config.js';
import type { Logger } from '../logging.js';

/* ------------------------------------------------------------------ */
/* Frontmatter / cache models                                          */
/* ------------------------------------------------------------------ */

/**
 * Schema-3 composite-doc frontmatter (canonical key order). Composites
 * NEVER have a man page, so `manRef` and `manPagePath` are literal
 * `null` — they appear in the frontmatter so consumers can rely on the
 * shape being uniform across schema-2 (member docs) and schema-3
 * (composite docs).
 *
 * The literal types `schemaVersion: 3`, `composite: true`, `manRef:
 * null`, `manPagePath: null` are intentional and load-bearing for the
 * type-narrowing checks done by the cache reader.
 *
 * Plan-006 alias notes: §14.D refers to this same shape as
 * `CompositeSchemaV3Frontmatter`; this module exports both names so
 * either can be consumed without churn.
 */
export interface CompositeFrontmatter {
  readonly schemaVersion: 3;
  readonly composite: true;
  readonly compositeName: string;
  readonly members: readonly string[];
  readonly memberDigests: Readonly<Record<string, string>>;
  readonly synthesizedAt: string;        // ISO 8601 UTC
  readonly syntheticDigest: string;      // sha256 first 16 hex of canonicalised body
  readonly cliAgentVersion: string;      // semver of the cli-agent that synthesised
  readonly synthesisModel: string;       // "<vendor>:<modelId>"
  readonly activeProfile: string | null;
  readonly manRef: null;
  readonly manPagePath: null;
}

/** Plan-006 §14.D canonical name. Re-exported alias for the same shape. */
export type CompositeSchemaV3Frontmatter = CompositeFrontmatter;

/**
 * Composite registration manifest (one per registered composite under
 * `composites/<id>/manifest.json`). Records the artefacts the
 * synthesis produced and which distribution forms (a/b/c) the user
 * opted into so subsequent commands (`composite-list`,
 * `composite-show`, `composite-delete`) can introspect without
 * rerunning synthesis.
 */
export interface CompositeManifest {
  readonly schemaVersion: 1;
  readonly compositeName: string;
  readonly members: readonly string[];
  readonly memberDigests: Readonly<Record<string, string>>;
  readonly createdAt: string;
  readonly cliAgentVersion: string;
  /** Absolute path to the canonical schema-3 doc under
   * `<agentDir>/capabilities/composite/<id>.md`. */
  readonly capabilityDocPath: string;
  /** Distribution forms the synthesis emitted. Each flag is per-form;
   * a single synthesis run can opt into any subset. */
  readonly distribution: {
    readonly emitDoc: boolean;          // form a — schema-3 doc
    readonly emitWrapper: boolean;      // form b — POSIX shim under composites/<id>/
    readonly emitWrapperOnPath: boolean; // form b — symlink in ~/.local/bin/
    readonly registerVirtual: boolean;  // form c — virtual-tool registration
  };
}

/**
 * Logical reference to a member doc, used during synthesis input
 * gathering. Not stored on disk; constructed on the fly by U-SYNTH.
 */
export interface CompositeMemberRef {
  /** Canonical member name (the `--tool` argument value). */
  readonly name: string;
  /** Absolute path to the member's schema-2 capability doc, resolved
   * via `<agentDir>/capabilities/<name>.md`. */
  readonly docPath: string;
  /** sha256 first 16 hex of the canonicalised member-doc bytes (USER-*
   * blocks stripped). Same algorithm `canonicaliseMemberDoc` produces. */
  readonly digest: string;
}

/* ------------------------------------------------------------------ */
/* Composite as in-memory aggregate                                    */
/* ------------------------------------------------------------------ */

/**
 * Parsed schema-3 composite doc as four logical sections. The reader
 * (`readCompositeDoc`) returns this; the composer
 * (`composeCompositeDoc`) consumes the same shape.
 */
export interface Composite {
  readonly frontmatter: CompositeFrontmatter;
  readonly autoGeneratedBody: string;   // text between AUTO-GEN markers
  readonly userRecipes: string;         // text between USER-RECIPES markers
  readonly userNotes: string;           // text between USER-NOTES markers
}

/* ------------------------------------------------------------------ */
/* Synthesis pipeline I/O                                              */
/* ------------------------------------------------------------------ */

export interface Stage1Distillation {
  readonly memberName: string;
  /** Structured intent surface (~2 KB). Stage-2 input. */
  readonly content: string;
  /** Synthesis model that produced this distillation
   * (`<vendor>:<modelId>`). */
  readonly modelId: string;
  /** Stage-1 prompt template version pin; bumping invalidates the
   * distill cache. */
  readonly templateVersion: string;
  readonly createdAt: string;            // ISO 8601 UTC
}

export interface SynthesisInputs {
  readonly cfg: AgentConfig;
  /** Already-constructed BaseChatModel (caller calls `createLLM(cfg)`). */
  readonly llm: BaseChatModel;
  /** Sorted canonical member names — caller pre-sorts. */
  readonly members: readonly string[];
  /** Validated or auto-derived composite name. */
  readonly compositeName: string;
  /** When true, emit the prompts that WOULD be sent to the LLM and
   * exit 0 without spending a token or writing to disk. */
  readonly dryRun: boolean;
  /** Combined Stage-1 + Stage-2 token cap. */
  readonly budgetTokens: number;
  readonly logger: Logger;
}

export interface SynthesisResult {
  /** Full schema-3 markdown body, ready to write to disk. */
  readonly doc: string;
  readonly frontmatter: CompositeFrontmatter;
  /** Sum of Stage-1 + Stage-2 input + output tokens. Stage-1 distill
   * cache hits report 0 for that member. */
  readonly totalTokens: number;
  /** Top-level cache hit (cached doc returned without LLM contact);
   * NOT the per-member Stage-1 cache. */
  readonly cacheHit: boolean;
}

/* ------------------------------------------------------------------ */
/* Wrapper shim (form b)                                               */
/* ------------------------------------------------------------------ */

export interface CompositeWrapperShimSpec {
  readonly compositeName: string;
  readonly members: readonly string[];
  /** Absolute path to the cli-agent binary, resolved at synthesis time
   * so the shim survives `which cli-agent` changes after install. */
  readonly cliAgentBinPath: string;
  /** Absolute path to the mirror copy of the composite doc under
   * `<agentDir>/capabilities/<id>.md` (the consumer-side
   * `composeCapabilitiesSystemPrompt` reader picks it up unchanged). */
  readonly capabilityDocPath: string;
  /** `<agentDir>/composites/<id>/` — where the shim is written and
   * `manifest.json` lives. */
  readonly shimDir: string;
  readonly synthesizedAt: string;
}

/* ------------------------------------------------------------------ */
/* Virtual tool (form c)                                               */
/* ------------------------------------------------------------------ */

export type DispatchMode = 'child-process' | 'in-process';

export interface VirtualToolHandle {
  /** Composite id (matches manifest.compositeName). */
  readonly name: string;
  readonly manifest: CompositeManifest;
  /** Loaded from `manifest.capabilityDocPath` — the agent prompt's
   * tool-description text. */
  readonly description: string;
  readonly dispatch: (args: readonly string[]) => Promise<{
    exitCode: number;
    stdout: string;
    stderr: string;
  }>;
}

/* ------------------------------------------------------------------ */
/* Provider-agnostic prompt cache helper (U-CACHE)                     */
/* ------------------------------------------------------------------ */

export type ProviderFamily =
  | 'anthropic'
  | 'openai'
  | 'azure-openai'
  | 'azure-inference'
  | 'google-gemini'
  | 'litellm-anthropic'
  | 'litellm-openai'
  | 'ollama'
  | 'local-compat';

export interface SynthesisCacheOptions {
  readonly providerFamily: ProviderFamily;
  /** Messages 0..N-1 are marked for cache; the suffix (the live tail)
   * is not. Stage-2 sets this to `messages.length - 1` so only the
   * final user-turn is uncached. */
  readonly prefixEndIndex: number;
  /** Anthropic-only: 5-minute or 1-hour TTL. Ignored by all other
   * providers. */
  readonly anthropicTtl?: '5m' | '1h';
}

/* ------------------------------------------------------------------ */
/* Re-exports for convenience                                          */
/* ------------------------------------------------------------------ */

export type { BaseMessage, BaseChatModel, AgentConfig, Logger };
