/**
 * `profile-create <name>` — scaffold a new configuration profile.
 *
 * Modes:
 *   - default          → write the canonical commented stub from
 *                        `createProfileStub(name)`.
 *   - --from-current   → snapshot the current effective configuration
 *                        (without `flags.profile`) into the profile's
 *                        cliParams. Credential-shape keys are filtered.
 *
 * The destination file is created at mode 0600 (NFR-PROF-002). Refuses
 * to overwrite an existing file unless `--force` is passed.
 *
 * Spec: plan-005 §5 U-CLI; FR-PROF-010; AC-15.
 */

import fsp from 'node:fs/promises';
import path from 'node:path';
import {
  agentToolAgentsDir,
  bootstrapAgentDir,
  loadAgentConfig,
} from '../../config/agent-config.js';
import { ConfigurationError, UsageError } from '../../errors.js';
import {
  createProfileStub,
  detectAmbiguity,
  stringifyProfile,
} from '../../config/profile-codec.js';
import { validateProfileName } from '../../config/profile-loader.js';
import {
  CREDENTIAL_KEY_PATTERN,
  KNOWN_CLI_PARAMS,
  type Profile,
} from '../../config/profile-schema.js';

export interface ProfileCreateOpts {
  readonly fromCurrent?: boolean;
  readonly description?: string;
  readonly force?: boolean;
}

export async function runProfileCreate(
  name: string,
  opts: ProfileCreateOpts = {},
): Promise<void> {
  validateProfileName(name);

  const agentDir = agentToolAgentsDir();
  // Ensure profiles/ exists at mode 0700 (additive bootstrap).
  await bootstrapAgentDir(agentDir);

  const profilesDir = path.join(agentDir, 'profiles');
  const targetPath = path.join(profilesDir, `${name}.yaml`);

  // Refuse to overwrite unless --force. Also detect existing JSON twin
  // (E18 ambiguity guard at create time).
  const existing = detectAmbiguity(agentDir, name);
  const present = existing.yaml ?? existing.json;
  if (present && !opts.force) {
    throw new ConfigurationError('profile file', [present], {
      detail:
        `Profile '${name}' already exists at ${present}. ` +
        `Pass --force to overwrite, or pick a different name.`,
      profileName: name,
      existingPath: present,
    });
  }

  let body: string;
  if (opts.fromCurrent) {
    body = await renderFromCurrent(name, opts.description);
  } else {
    body = createProfileStub(name);
    // Inject description, if supplied, by inserting after `name: <name>`.
    if (opts.description) {
      body = body.replace(
        `name: ${name}\n`,
        `name: ${name}\ndescription: ${quoteForYaml(opts.description)}\n`,
      );
    }
  }

  await fsp.writeFile(targetPath, body, { mode: 0o600 });
  // Defensive chmod (writeFile ignores `mode` on existing files).
  try {
    await fsp.chmod(targetPath, 0o600);
  } catch {
    /* best effort on Windows */
  }

  process.stdout.write(`Created profile '${name}' at ${targetPath}\n`);
}

/**
 * Snapshot the resolved config (without `flags.profile` set) into a
 * Profile object's cliParams, then stringify. Drops any key that
 * matches the credential-shape regex (E11 defence-in-depth even though
 * `loadAgentConfig` does not expose secrets directly).
 */
async function renderFromCurrent(
  name: string,
  description: string | undefined,
): Promise<string> {
  // Pass an empty flags bag so we capture the non-profile effective
  // config (shell env / agent-dir .env / local .env / config.json /
  // built-in defaults). Explicitly DO NOT propagate `flags.profile`.
  const cfg = await loadAgentConfig(
    {},
    { shellEnv: process.env, cwd: process.cwd() },
  );

  // Snapshot the documented cliParams keys. Any value that is undefined
  // is omitted entirely so we don't write `key: null` everywhere.
  const snapshot: Record<string, unknown> = {};
  const candidate: Record<string, unknown> = {
    provider: cfg.provider,
    model: cfg.model,
    temperature: cfg.temperature,
    maxIterations: cfg.maxSteps,
    workingDir: cfg.fileEdit.root,
    webSearchBackend: cfg.webSearchBackend ?? cfg.webSearch.backend,
    allowMutations: cfg.allowMutations,
  };
  for (const [k, v] of Object.entries(candidate)) {
    if (v === undefined) continue;
    if (CREDENTIAL_KEY_PATTERN.test(k)) continue;
    if (!KNOWN_CLI_PARAMS.has(k)) continue; // forward-compat safety
    snapshot[k] = v;
  }

  const profile: Profile = {
    name,
    description,
    schemaVersion: 1,
    cliParams: snapshot,
  };

  // Header comment + body.
  const header =
    `# cli-agent profile: ${name}\n` +
    `# Generated by 'profile-create --from-current' on ${new Date().toISOString()}.\n` +
    `# Snapshot of the current effective config (without any active profile).\n` +
    `# Edit freely; comments are preserved on read but stripped on re-serialise.\n\n`;
  return header + stringifyProfile(profile);
}

function quoteForYaml(s: string): string {
  // Use a simple double-quoted form when the description contains
  // characters that would otherwise need escaping; plain otherwise.
  if (/^[A-Za-z0-9 _.\-,;:()/]+$/.test(s)) return s;
  return JSON.stringify(s);
}

// Re-export UsageError for callers that want to differentiate the
// validateProfileName failure mode in tests.
export { UsageError };
