/**
 * `composite-show <name>` — print the cached schema-3 composite doc.
 *
 * Default output: raw markdown body verbatim.
 * `--json` opts into a structured payload (frontmatter + bodies).
 *
 * Spec: plan-006 §14.E; FR-CMP-022; AC-22.
 *
 * Exit codes:
 *   0  success
 *   2  composite not found
 *   3  composite present but malformed/integrity-failed (read returns
 *       a non-ok result)
 */

import { agentCompositeCapabilitiesDir } from '../../config/agent-config.js';
import { readCompositeDoc } from '../../agent/composite/cache.js';
import { ConfigurationError, UsageError } from '../../errors.js';
import { canonicalDocPathFor, emitJson, validateCompositeName } from './shared.js';

export interface CompositeShowOpts {
  readonly json?: boolean;
  /** Test seam — overrides the resolved composite-capabilities dir. */
  readonly compositeCapabilitiesDirOverride?: string;
}

export async function runCompositeShow(
  name: string,
  opts: CompositeShowOpts = {},
): Promise<void> {
  validateCompositeName(name);

  // Read-only — does NOT need an LLM provider configured.
  const dir =
    opts.compositeCapabilitiesDirOverride ?? agentCompositeCapabilitiesDir();
  const docPath = canonicalDocPathFor(dir, name);

  const r = await readCompositeDoc(docPath);
  if (!r.ok) {
    if (r.reason === 'missing') {
      throw new UsageError(
        `composite '${name}' not found at ${docPath}`,
        { compositeName: name, path: docPath },
      );
    }
    throw new ConfigurationError(
      `composite '${name}' is not readable as schema-3`,
      [docPath],
      {
        reason: r.reason,
        details: r.details,
      },
    );
  }

  if (opts.json) {
    emitJson({
      compositeName: r.doc.frontmatter.compositeName,
      frontmatter: r.doc.frontmatter,
      body: r.doc.autoGeneratedBody,
      recipes: r.doc.userRecipes,
      notes: r.doc.userNotes,
      path: docPath,
    });
    return;
  }

  process.stdout.write(r.doc.raw);
  if (!r.doc.raw.endsWith('\n')) process.stdout.write('\n');
}
